#!/usr/bin/env python

import os
import sys 

#this can cause problems with old versions of enable
#os.environ['QT_API']='pyqt'

scriptdir=os.getcwd()
os.chdir(os.path.join(os.path.dirname(os.path.realpath(__file__)),'cvu'))
os.system('python main.py %s '%scriptdir+" ".join(sys.argv[1:]))
